// Auto-generated data mirror for Cloudflare Pages Functions.
// Keep this file aligned with files in /data.

export const countries = [
  {
    "name": "Afghanistan",
    "official_name": "Islamic Republic of Afghanistan",
    "common_name": "Afghanistan",
    "alpha2": "AF",
    "alpha3": "AFG",
    "numeric": "004",
    "slug": "afghanistan",
    "flag": "🇦🇫",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Albania",
    "official_name": "Republic of Albania",
    "common_name": "Albania",
    "alpha2": "AL",
    "alpha3": "ALB",
    "numeric": "008",
    "slug": "albania",
    "flag": "🇦🇱",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Algeria",
    "official_name": "People's Democratic Republic of Algeria",
    "common_name": "Algeria",
    "alpha2": "DZ",
    "alpha3": "DZA",
    "numeric": "012",
    "slug": "algeria",
    "flag": "🇩🇿",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "American Samoa",
    "official_name": "American Samoa",
    "common_name": "American Samoa",
    "alpha2": "AS",
    "alpha3": "ASM",
    "numeric": "016",
    "slug": "american-samoa",
    "flag": "🇦🇸",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Andorra",
    "official_name": "Principality of Andorra",
    "common_name": "Andorra",
    "alpha2": "AD",
    "alpha3": "AND",
    "numeric": "020",
    "slug": "andorra",
    "flag": "🇦🇩",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Angola",
    "official_name": "Republic of Angola",
    "common_name": "Angola",
    "alpha2": "AO",
    "alpha3": "AGO",
    "numeric": "024",
    "slug": "angola",
    "flag": "🇦🇴",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Anguilla",
    "official_name": "Anguilla",
    "common_name": "Anguilla",
    "alpha2": "AI",
    "alpha3": "AIA",
    "numeric": "660",
    "slug": "anguilla",
    "flag": "🇦🇮",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Antarctica",
    "official_name": "Antarctica",
    "common_name": "Antarctica",
    "alpha2": "AQ",
    "alpha3": "ATA",
    "numeric": "010",
    "slug": "antarctica",
    "flag": "🇦🇶",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Antigua and Barbuda",
    "official_name": "Antigua and Barbuda",
    "common_name": "Antigua and Barbuda",
    "alpha2": "AG",
    "alpha3": "ATG",
    "numeric": "028",
    "slug": "antigua-and-barbuda",
    "flag": "🇦🇬",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Argentina",
    "official_name": "Argentine Republic",
    "common_name": "Argentina",
    "alpha2": "AR",
    "alpha3": "ARG",
    "numeric": "032",
    "slug": "argentina",
    "flag": "🇦🇷",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Armenia",
    "official_name": "Republic of Armenia",
    "common_name": "Armenia",
    "alpha2": "AM",
    "alpha3": "ARM",
    "numeric": "051",
    "slug": "armenia",
    "flag": "🇦🇲",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Aruba",
    "official_name": "Aruba",
    "common_name": "Aruba",
    "alpha2": "AW",
    "alpha3": "ABW",
    "numeric": "533",
    "slug": "aruba",
    "flag": "🇦🇼",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Australia",
    "official_name": "Australia",
    "common_name": "Australia",
    "alpha2": "AU",
    "alpha3": "AUS",
    "numeric": "036",
    "slug": "australia",
    "flag": "🇦🇺",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Austria",
    "official_name": "Republic of Austria",
    "common_name": "Austria",
    "alpha2": "AT",
    "alpha3": "AUT",
    "numeric": "040",
    "slug": "austria",
    "flag": "🇦🇹",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Azerbaijan",
    "official_name": "Republic of Azerbaijan",
    "common_name": "Azerbaijan",
    "alpha2": "AZ",
    "alpha3": "AZE",
    "numeric": "031",
    "slug": "azerbaijan",
    "flag": "🇦🇿",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Bahamas",
    "official_name": "Commonwealth of the Bahamas",
    "common_name": "Bahamas",
    "alpha2": "BS",
    "alpha3": "BHS",
    "numeric": "044",
    "slug": "bahamas",
    "flag": "🇧🇸",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Bahrain",
    "official_name": "Kingdom of Bahrain",
    "common_name": "Bahrain",
    "alpha2": "BH",
    "alpha3": "BHR",
    "numeric": "048",
    "slug": "bahrain",
    "flag": "🇧🇭",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Bangladesh",
    "official_name": "People's Republic of Bangladesh",
    "common_name": "Bangladesh",
    "alpha2": "BD",
    "alpha3": "BGD",
    "numeric": "050",
    "slug": "bangladesh",
    "flag": "🇧🇩",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Barbados",
    "official_name": "Barbados",
    "common_name": "Barbados",
    "alpha2": "BB",
    "alpha3": "BRB",
    "numeric": "052",
    "slug": "barbados",
    "flag": "🇧🇧",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Belarus",
    "official_name": "Republic of Belarus",
    "common_name": "Belarus",
    "alpha2": "BY",
    "alpha3": "BLR",
    "numeric": "112",
    "slug": "belarus",
    "flag": "🇧🇾",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Belgium",
    "official_name": "Kingdom of Belgium",
    "common_name": "Belgium",
    "alpha2": "BE",
    "alpha3": "BEL",
    "numeric": "056",
    "slug": "belgium",
    "flag": "🇧🇪",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Belize",
    "official_name": "Belize",
    "common_name": "Belize",
    "alpha2": "BZ",
    "alpha3": "BLZ",
    "numeric": "084",
    "slug": "belize",
    "flag": "🇧🇿",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Benin",
    "official_name": "Republic of Benin",
    "common_name": "Benin",
    "alpha2": "BJ",
    "alpha3": "BEN",
    "numeric": "204",
    "slug": "benin",
    "flag": "🇧🇯",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Bermuda",
    "official_name": "Bermuda",
    "common_name": "Bermuda",
    "alpha2": "BM",
    "alpha3": "BMU",
    "numeric": "060",
    "slug": "bermuda",
    "flag": "🇧🇲",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Bhutan",
    "official_name": "Kingdom of Bhutan",
    "common_name": "Bhutan",
    "alpha2": "BT",
    "alpha3": "BTN",
    "numeric": "064",
    "slug": "bhutan",
    "flag": "🇧🇹",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Bolivia, Plurinational State of",
    "official_name": "Plurinational State of Bolivia",
    "common_name": "Bolivia",
    "alpha2": "BO",
    "alpha3": "BOL",
    "numeric": "068",
    "slug": "bolivia-plurinational-state-of",
    "flag": "🇧🇴",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Bonaire, Sint Eustatius and Saba",
    "official_name": "Bonaire, Sint Eustatius and Saba",
    "common_name": "Bonaire, Sint Eustatius and Saba",
    "alpha2": "BQ",
    "alpha3": "BES",
    "numeric": "535",
    "slug": "bonaire-sint-eustatius-and-saba",
    "flag": "🇧🇶",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Bosnia and Herzegovina",
    "official_name": "Republic of Bosnia and Herzegovina",
    "common_name": "Bosnia and Herzegovina",
    "alpha2": "BA",
    "alpha3": "BIH",
    "numeric": "070",
    "slug": "bosnia-and-herzegovina",
    "flag": "🇧🇦",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Botswana",
    "official_name": "Republic of Botswana",
    "common_name": "Botswana",
    "alpha2": "BW",
    "alpha3": "BWA",
    "numeric": "072",
    "slug": "botswana",
    "flag": "🇧🇼",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Bouvet Island",
    "official_name": "Bouvet Island",
    "common_name": "Bouvet Island",
    "alpha2": "BV",
    "alpha3": "BVT",
    "numeric": "074",
    "slug": "bouvet-island",
    "flag": "🇧🇻",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Brazil",
    "official_name": "Federative Republic of Brazil",
    "common_name": "Brazil",
    "alpha2": "BR",
    "alpha3": "BRA",
    "numeric": "076",
    "slug": "brazil",
    "flag": "🇧🇷",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "British Indian Ocean Territory",
    "official_name": "British Indian Ocean Territory",
    "common_name": "British Indian Ocean Territory",
    "alpha2": "IO",
    "alpha3": "IOT",
    "numeric": "086",
    "slug": "british-indian-ocean-territory",
    "flag": "🇮🇴",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Brunei Darussalam",
    "official_name": "Brunei Darussalam",
    "common_name": "Brunei Darussalam",
    "alpha2": "BN",
    "alpha3": "BRN",
    "numeric": "096",
    "slug": "brunei-darussalam",
    "flag": "🇧🇳",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Bulgaria",
    "official_name": "Republic of Bulgaria",
    "common_name": "Bulgaria",
    "alpha2": "BG",
    "alpha3": "BGR",
    "numeric": "100",
    "slug": "bulgaria",
    "flag": "🇧🇬",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Burkina Faso",
    "official_name": "Burkina Faso",
    "common_name": "Burkina Faso",
    "alpha2": "BF",
    "alpha3": "BFA",
    "numeric": "854",
    "slug": "burkina-faso",
    "flag": "🇧🇫",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Burundi",
    "official_name": "Republic of Burundi",
    "common_name": "Burundi",
    "alpha2": "BI",
    "alpha3": "BDI",
    "numeric": "108",
    "slug": "burundi",
    "flag": "🇧🇮",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Cabo Verde",
    "official_name": "Republic of Cabo Verde",
    "common_name": "Cabo Verde",
    "alpha2": "CV",
    "alpha3": "CPV",
    "numeric": "132",
    "slug": "cabo-verde",
    "flag": "🇨🇻",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Cambodia",
    "official_name": "Kingdom of Cambodia",
    "common_name": "Cambodia",
    "alpha2": "KH",
    "alpha3": "KHM",
    "numeric": "116",
    "slug": "cambodia",
    "flag": "🇰🇭",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Cameroon",
    "official_name": "Republic of Cameroon",
    "common_name": "Cameroon",
    "alpha2": "CM",
    "alpha3": "CMR",
    "numeric": "120",
    "slug": "cameroon",
    "flag": "🇨🇲",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Canada",
    "official_name": "Canada",
    "common_name": "Canada",
    "alpha2": "CA",
    "alpha3": "CAN",
    "numeric": "124",
    "slug": "canada",
    "flag": "🇨🇦",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Cayman Islands",
    "official_name": "Cayman Islands",
    "common_name": "Cayman Islands",
    "alpha2": "KY",
    "alpha3": "CYM",
    "numeric": "136",
    "slug": "cayman-islands",
    "flag": "🇰🇾",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Central African Republic",
    "official_name": "Central African Republic",
    "common_name": "Central African Republic",
    "alpha2": "CF",
    "alpha3": "CAF",
    "numeric": "140",
    "slug": "central-african-republic",
    "flag": "🇨🇫",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Chad",
    "official_name": "Republic of Chad",
    "common_name": "Chad",
    "alpha2": "TD",
    "alpha3": "TCD",
    "numeric": "148",
    "slug": "chad",
    "flag": "🇹🇩",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Chile",
    "official_name": "Republic of Chile",
    "common_name": "Chile",
    "alpha2": "CL",
    "alpha3": "CHL",
    "numeric": "152",
    "slug": "chile",
    "flag": "🇨🇱",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "China",
    "official_name": "People's Republic of China",
    "common_name": "China",
    "alpha2": "CN",
    "alpha3": "CHN",
    "numeric": "156",
    "slug": "china",
    "flag": "🇨🇳",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Christmas Island",
    "official_name": "Christmas Island",
    "common_name": "Christmas Island",
    "alpha2": "CX",
    "alpha3": "CXR",
    "numeric": "162",
    "slug": "christmas-island",
    "flag": "🇨🇽",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Cocos (Keeling) Islands",
    "official_name": "Cocos (Keeling) Islands",
    "common_name": "Cocos (Keeling) Islands",
    "alpha2": "CC",
    "alpha3": "CCK",
    "numeric": "166",
    "slug": "cocos-keeling-islands",
    "flag": "🇨🇨",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Colombia",
    "official_name": "Republic of Colombia",
    "common_name": "Colombia",
    "alpha2": "CO",
    "alpha3": "COL",
    "numeric": "170",
    "slug": "colombia",
    "flag": "🇨🇴",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Comoros",
    "official_name": "Union of the Comoros",
    "common_name": "Comoros",
    "alpha2": "KM",
    "alpha3": "COM",
    "numeric": "174",
    "slug": "comoros",
    "flag": "🇰🇲",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Congo",
    "official_name": "Republic of the Congo",
    "common_name": "Congo",
    "alpha2": "CG",
    "alpha3": "COG",
    "numeric": "178",
    "slug": "congo",
    "flag": "🇨🇬",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Congo, The Democratic Republic of the",
    "official_name": "Congo, The Democratic Republic of the",
    "common_name": "Congo, The Democratic Republic of the",
    "alpha2": "CD",
    "alpha3": "COD",
    "numeric": "180",
    "slug": "congo-the-democratic-republic-of-the",
    "flag": "🇨🇩",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Cook Islands",
    "official_name": "Cook Islands",
    "common_name": "Cook Islands",
    "alpha2": "CK",
    "alpha3": "COK",
    "numeric": "184",
    "slug": "cook-islands",
    "flag": "🇨🇰",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Costa Rica",
    "official_name": "Republic of Costa Rica",
    "common_name": "Costa Rica",
    "alpha2": "CR",
    "alpha3": "CRI",
    "numeric": "188",
    "slug": "costa-rica",
    "flag": "🇨🇷",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Croatia",
    "official_name": "Republic of Croatia",
    "common_name": "Croatia",
    "alpha2": "HR",
    "alpha3": "HRV",
    "numeric": "191",
    "slug": "croatia",
    "flag": "🇭🇷",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Cuba",
    "official_name": "Republic of Cuba",
    "common_name": "Cuba",
    "alpha2": "CU",
    "alpha3": "CUB",
    "numeric": "192",
    "slug": "cuba",
    "flag": "🇨🇺",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Curaçao",
    "official_name": "Curaçao",
    "common_name": "Curaçao",
    "alpha2": "CW",
    "alpha3": "CUW",
    "numeric": "531",
    "slug": "cura-ao",
    "flag": "🇨🇼",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Cyprus",
    "official_name": "Republic of Cyprus",
    "common_name": "Cyprus",
    "alpha2": "CY",
    "alpha3": "CYP",
    "numeric": "196",
    "slug": "cyprus",
    "flag": "🇨🇾",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Czechia",
    "official_name": "Czech Republic",
    "common_name": "Czechia",
    "alpha2": "CZ",
    "alpha3": "CZE",
    "numeric": "203",
    "slug": "czechia",
    "flag": "🇨🇿",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Côte d'Ivoire",
    "official_name": "Republic of Côte d'Ivoire",
    "common_name": "Côte d'Ivoire",
    "alpha2": "CI",
    "alpha3": "CIV",
    "numeric": "384",
    "slug": "c-te-d-ivoire",
    "flag": "🇨🇮",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Denmark",
    "official_name": "Kingdom of Denmark",
    "common_name": "Denmark",
    "alpha2": "DK",
    "alpha3": "DNK",
    "numeric": "208",
    "slug": "denmark",
    "flag": "🇩🇰",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Djibouti",
    "official_name": "Republic of Djibouti",
    "common_name": "Djibouti",
    "alpha2": "DJ",
    "alpha3": "DJI",
    "numeric": "262",
    "slug": "djibouti",
    "flag": "🇩🇯",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Dominica",
    "official_name": "Commonwealth of Dominica",
    "common_name": "Dominica",
    "alpha2": "DM",
    "alpha3": "DMA",
    "numeric": "212",
    "slug": "dominica",
    "flag": "🇩🇲",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Dominican Republic",
    "official_name": "Dominican Republic",
    "common_name": "Dominican Republic",
    "alpha2": "DO",
    "alpha3": "DOM",
    "numeric": "214",
    "slug": "dominican-republic",
    "flag": "🇩🇴",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Ecuador",
    "official_name": "Republic of Ecuador",
    "common_name": "Ecuador",
    "alpha2": "EC",
    "alpha3": "ECU",
    "numeric": "218",
    "slug": "ecuador",
    "flag": "🇪🇨",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Egypt",
    "official_name": "Arab Republic of Egypt",
    "common_name": "Egypt",
    "alpha2": "EG",
    "alpha3": "EGY",
    "numeric": "818",
    "slug": "egypt",
    "flag": "🇪🇬",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "El Salvador",
    "official_name": "Republic of El Salvador",
    "common_name": "El Salvador",
    "alpha2": "SV",
    "alpha3": "SLV",
    "numeric": "222",
    "slug": "el-salvador",
    "flag": "🇸🇻",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Equatorial Guinea",
    "official_name": "Republic of Equatorial Guinea",
    "common_name": "Equatorial Guinea",
    "alpha2": "GQ",
    "alpha3": "GNQ",
    "numeric": "226",
    "slug": "equatorial-guinea",
    "flag": "🇬🇶",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Eritrea",
    "official_name": "the State of Eritrea",
    "common_name": "Eritrea",
    "alpha2": "ER",
    "alpha3": "ERI",
    "numeric": "232",
    "slug": "eritrea",
    "flag": "🇪🇷",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Estonia",
    "official_name": "Republic of Estonia",
    "common_name": "Estonia",
    "alpha2": "EE",
    "alpha3": "EST",
    "numeric": "233",
    "slug": "estonia",
    "flag": "🇪🇪",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Eswatini",
    "official_name": "Kingdom of Eswatini",
    "common_name": "Eswatini",
    "alpha2": "SZ",
    "alpha3": "SWZ",
    "numeric": "748",
    "slug": "eswatini",
    "flag": "🇸🇿",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Ethiopia",
    "official_name": "Federal Democratic Republic of Ethiopia",
    "common_name": "Ethiopia",
    "alpha2": "ET",
    "alpha3": "ETH",
    "numeric": "231",
    "slug": "ethiopia",
    "flag": "🇪🇹",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Falkland Islands (Malvinas)",
    "official_name": "Falkland Islands (Malvinas)",
    "common_name": "Falkland Islands (Malvinas)",
    "alpha2": "FK",
    "alpha3": "FLK",
    "numeric": "238",
    "slug": "falkland-islands-malvinas",
    "flag": "🇫🇰",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Faroe Islands",
    "official_name": "Faroe Islands",
    "common_name": "Faroe Islands",
    "alpha2": "FO",
    "alpha3": "FRO",
    "numeric": "234",
    "slug": "faroe-islands",
    "flag": "🇫🇴",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Fiji",
    "official_name": "Republic of Fiji",
    "common_name": "Fiji",
    "alpha2": "FJ",
    "alpha3": "FJI",
    "numeric": "242",
    "slug": "fiji",
    "flag": "🇫🇯",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Finland",
    "official_name": "Republic of Finland",
    "common_name": "Finland",
    "alpha2": "FI",
    "alpha3": "FIN",
    "numeric": "246",
    "slug": "finland",
    "flag": "🇫🇮",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "France",
    "official_name": "French Republic",
    "common_name": "France",
    "alpha2": "FR",
    "alpha3": "FRA",
    "numeric": "250",
    "slug": "france",
    "flag": "🇫🇷",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "French Guiana",
    "official_name": "French Guiana",
    "common_name": "French Guiana",
    "alpha2": "GF",
    "alpha3": "GUF",
    "numeric": "254",
    "slug": "french-guiana",
    "flag": "🇬🇫",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "French Polynesia",
    "official_name": "French Polynesia",
    "common_name": "French Polynesia",
    "alpha2": "PF",
    "alpha3": "PYF",
    "numeric": "258",
    "slug": "french-polynesia",
    "flag": "🇵🇫",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "French Southern Territories",
    "official_name": "French Southern Territories",
    "common_name": "French Southern Territories",
    "alpha2": "TF",
    "alpha3": "ATF",
    "numeric": "260",
    "slug": "french-southern-territories",
    "flag": "🇹🇫",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Gabon",
    "official_name": "Gabonese Republic",
    "common_name": "Gabon",
    "alpha2": "GA",
    "alpha3": "GAB",
    "numeric": "266",
    "slug": "gabon",
    "flag": "🇬🇦",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Gambia",
    "official_name": "Republic of the Gambia",
    "common_name": "Gambia",
    "alpha2": "GM",
    "alpha3": "GMB",
    "numeric": "270",
    "slug": "gambia",
    "flag": "🇬🇲",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Georgia",
    "official_name": "Georgia",
    "common_name": "Georgia",
    "alpha2": "GE",
    "alpha3": "GEO",
    "numeric": "268",
    "slug": "georgia",
    "flag": "🇬🇪",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Germany",
    "official_name": "Federal Republic of Germany",
    "common_name": "Germany",
    "alpha2": "DE",
    "alpha3": "DEU",
    "numeric": "276",
    "slug": "germany",
    "flag": "🇩🇪",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Ghana",
    "official_name": "Republic of Ghana",
    "common_name": "Ghana",
    "alpha2": "GH",
    "alpha3": "GHA",
    "numeric": "288",
    "slug": "ghana",
    "flag": "🇬🇭",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Gibraltar",
    "official_name": "Gibraltar",
    "common_name": "Gibraltar",
    "alpha2": "GI",
    "alpha3": "GIB",
    "numeric": "292",
    "slug": "gibraltar",
    "flag": "🇬🇮",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Greece",
    "official_name": "Hellenic Republic",
    "common_name": "Greece",
    "alpha2": "GR",
    "alpha3": "GRC",
    "numeric": "300",
    "slug": "greece",
    "flag": "🇬🇷",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Greenland",
    "official_name": "Greenland",
    "common_name": "Greenland",
    "alpha2": "GL",
    "alpha3": "GRL",
    "numeric": "304",
    "slug": "greenland",
    "flag": "🇬🇱",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Grenada",
    "official_name": "Grenada",
    "common_name": "Grenada",
    "alpha2": "GD",
    "alpha3": "GRD",
    "numeric": "308",
    "slug": "grenada",
    "flag": "🇬🇩",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Guadeloupe",
    "official_name": "Guadeloupe",
    "common_name": "Guadeloupe",
    "alpha2": "GP",
    "alpha3": "GLP",
    "numeric": "312",
    "slug": "guadeloupe",
    "flag": "🇬🇵",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Guam",
    "official_name": "Guam",
    "common_name": "Guam",
    "alpha2": "GU",
    "alpha3": "GUM",
    "numeric": "316",
    "slug": "guam",
    "flag": "🇬🇺",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Guatemala",
    "official_name": "Republic of Guatemala",
    "common_name": "Guatemala",
    "alpha2": "GT",
    "alpha3": "GTM",
    "numeric": "320",
    "slug": "guatemala",
    "flag": "🇬🇹",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Guernsey",
    "official_name": "Guernsey",
    "common_name": "Guernsey",
    "alpha2": "GG",
    "alpha3": "GGY",
    "numeric": "831",
    "slug": "guernsey",
    "flag": "🇬🇬",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Guinea",
    "official_name": "Republic of Guinea",
    "common_name": "Guinea",
    "alpha2": "GN",
    "alpha3": "GIN",
    "numeric": "324",
    "slug": "guinea",
    "flag": "🇬🇳",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Guinea-Bissau",
    "official_name": "Republic of Guinea-Bissau",
    "common_name": "Guinea-Bissau",
    "alpha2": "GW",
    "alpha3": "GNB",
    "numeric": "624",
    "slug": "guinea-bissau",
    "flag": "🇬🇼",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Guyana",
    "official_name": "Republic of Guyana",
    "common_name": "Guyana",
    "alpha2": "GY",
    "alpha3": "GUY",
    "numeric": "328",
    "slug": "guyana",
    "flag": "🇬🇾",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Haiti",
    "official_name": "Republic of Haiti",
    "common_name": "Haiti",
    "alpha2": "HT",
    "alpha3": "HTI",
    "numeric": "332",
    "slug": "haiti",
    "flag": "🇭🇹",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Heard Island and McDonald Islands",
    "official_name": "Heard Island and McDonald Islands",
    "common_name": "Heard Island and McDonald Islands",
    "alpha2": "HM",
    "alpha3": "HMD",
    "numeric": "334",
    "slug": "heard-island-and-mcdonald-islands",
    "flag": "🇭🇲",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Holy See (Vatican City State)",
    "official_name": "Holy See (Vatican City State)",
    "common_name": "Holy See (Vatican City State)",
    "alpha2": "VA",
    "alpha3": "VAT",
    "numeric": "336",
    "slug": "holy-see-vatican-city-state",
    "flag": "🇻🇦",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Honduras",
    "official_name": "Republic of Honduras",
    "common_name": "Honduras",
    "alpha2": "HN",
    "alpha3": "HND",
    "numeric": "340",
    "slug": "honduras",
    "flag": "🇭🇳",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Hong Kong",
    "official_name": "Hong Kong Special Administrative Region of China",
    "common_name": "Hong Kong",
    "alpha2": "HK",
    "alpha3": "HKG",
    "numeric": "344",
    "slug": "hong-kong",
    "flag": "🇭🇰",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Hungary",
    "official_name": "Hungary",
    "common_name": "Hungary",
    "alpha2": "HU",
    "alpha3": "HUN",
    "numeric": "348",
    "slug": "hungary",
    "flag": "🇭🇺",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Iceland",
    "official_name": "Republic of Iceland",
    "common_name": "Iceland",
    "alpha2": "IS",
    "alpha3": "ISL",
    "numeric": "352",
    "slug": "iceland",
    "flag": "🇮🇸",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "India",
    "official_name": "Republic of India",
    "common_name": "India",
    "alpha2": "IN",
    "alpha3": "IND",
    "numeric": "356",
    "slug": "india",
    "flag": "🇮🇳",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Indonesia",
    "official_name": "Republic of Indonesia",
    "common_name": "Indonesia",
    "alpha2": "ID",
    "alpha3": "IDN",
    "numeric": "360",
    "slug": "indonesia",
    "flag": "🇮🇩",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Iran, Islamic Republic of",
    "official_name": "Islamic Republic of Iran",
    "common_name": "Iran",
    "alpha2": "IR",
    "alpha3": "IRN",
    "numeric": "364",
    "slug": "iran-islamic-republic-of",
    "flag": "🇮🇷",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Iraq",
    "official_name": "Republic of Iraq",
    "common_name": "Iraq",
    "alpha2": "IQ",
    "alpha3": "IRQ",
    "numeric": "368",
    "slug": "iraq",
    "flag": "🇮🇶",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Ireland",
    "official_name": "Ireland",
    "common_name": "Ireland",
    "alpha2": "IE",
    "alpha3": "IRL",
    "numeric": "372",
    "slug": "ireland",
    "flag": "🇮🇪",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Isle of Man",
    "official_name": "Isle of Man",
    "common_name": "Isle of Man",
    "alpha2": "IM",
    "alpha3": "IMN",
    "numeric": "833",
    "slug": "isle-of-man",
    "flag": "🇮🇲",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Israel",
    "official_name": "State of Israel",
    "common_name": "Israel",
    "alpha2": "IL",
    "alpha3": "ISR",
    "numeric": "376",
    "slug": "israel",
    "flag": "🇮🇱",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Italy",
    "official_name": "Italian Republic",
    "common_name": "Italy",
    "alpha2": "IT",
    "alpha3": "ITA",
    "numeric": "380",
    "slug": "italy",
    "flag": "🇮🇹",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Jamaica",
    "official_name": "Jamaica",
    "common_name": "Jamaica",
    "alpha2": "JM",
    "alpha3": "JAM",
    "numeric": "388",
    "slug": "jamaica",
    "flag": "🇯🇲",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Japan",
    "official_name": "Japan",
    "common_name": "Japan",
    "alpha2": "JP",
    "alpha3": "JPN",
    "numeric": "392",
    "slug": "japan",
    "flag": "🇯🇵",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Jersey",
    "official_name": "Jersey",
    "common_name": "Jersey",
    "alpha2": "JE",
    "alpha3": "JEY",
    "numeric": "832",
    "slug": "jersey",
    "flag": "🇯🇪",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Jordan",
    "official_name": "Hashemite Kingdom of Jordan",
    "common_name": "Jordan",
    "alpha2": "JO",
    "alpha3": "JOR",
    "numeric": "400",
    "slug": "jordan",
    "flag": "🇯🇴",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Kazakhstan",
    "official_name": "Republic of Kazakhstan",
    "common_name": "Kazakhstan",
    "alpha2": "KZ",
    "alpha3": "KAZ",
    "numeric": "398",
    "slug": "kazakhstan",
    "flag": "🇰🇿",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Kenya",
    "official_name": "Republic of Kenya",
    "common_name": "Kenya",
    "alpha2": "KE",
    "alpha3": "KEN",
    "numeric": "404",
    "slug": "kenya",
    "flag": "🇰🇪",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Kiribati",
    "official_name": "Republic of Kiribati",
    "common_name": "Kiribati",
    "alpha2": "KI",
    "alpha3": "KIR",
    "numeric": "296",
    "slug": "kiribati",
    "flag": "🇰🇮",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Korea, Democratic People's Republic of",
    "official_name": "Democratic People's Republic of Korea",
    "common_name": "North Korea",
    "alpha2": "KP",
    "alpha3": "PRK",
    "numeric": "408",
    "slug": "korea-democratic-people-s-republic-of",
    "flag": "🇰🇵",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Korea, Republic of",
    "official_name": "Korea, Republic of",
    "common_name": "South Korea",
    "alpha2": "KR",
    "alpha3": "KOR",
    "numeric": "410",
    "slug": "korea-republic-of",
    "flag": "🇰🇷",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Kuwait",
    "official_name": "State of Kuwait",
    "common_name": "Kuwait",
    "alpha2": "KW",
    "alpha3": "KWT",
    "numeric": "414",
    "slug": "kuwait",
    "flag": "🇰🇼",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Kyrgyzstan",
    "official_name": "Kyrgyz Republic",
    "common_name": "Kyrgyzstan",
    "alpha2": "KG",
    "alpha3": "KGZ",
    "numeric": "417",
    "slug": "kyrgyzstan",
    "flag": "🇰🇬",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Lao People's Democratic Republic",
    "official_name": "Lao People's Democratic Republic",
    "common_name": "Laos",
    "alpha2": "LA",
    "alpha3": "LAO",
    "numeric": "418",
    "slug": "lao-people-s-democratic-republic",
    "flag": "🇱🇦",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Latvia",
    "official_name": "Republic of Latvia",
    "common_name": "Latvia",
    "alpha2": "LV",
    "alpha3": "LVA",
    "numeric": "428",
    "slug": "latvia",
    "flag": "🇱🇻",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Lebanon",
    "official_name": "Lebanese Republic",
    "common_name": "Lebanon",
    "alpha2": "LB",
    "alpha3": "LBN",
    "numeric": "422",
    "slug": "lebanon",
    "flag": "🇱🇧",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Lesotho",
    "official_name": "Kingdom of Lesotho",
    "common_name": "Lesotho",
    "alpha2": "LS",
    "alpha3": "LSO",
    "numeric": "426",
    "slug": "lesotho",
    "flag": "🇱🇸",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Liberia",
    "official_name": "Republic of Liberia",
    "common_name": "Liberia",
    "alpha2": "LR",
    "alpha3": "LBR",
    "numeric": "430",
    "slug": "liberia",
    "flag": "🇱🇷",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Libya",
    "official_name": "Libya",
    "common_name": "Libya",
    "alpha2": "LY",
    "alpha3": "LBY",
    "numeric": "434",
    "slug": "libya",
    "flag": "🇱🇾",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Liechtenstein",
    "official_name": "Principality of Liechtenstein",
    "common_name": "Liechtenstein",
    "alpha2": "LI",
    "alpha3": "LIE",
    "numeric": "438",
    "slug": "liechtenstein",
    "flag": "🇱🇮",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Lithuania",
    "official_name": "Republic of Lithuania",
    "common_name": "Lithuania",
    "alpha2": "LT",
    "alpha3": "LTU",
    "numeric": "440",
    "slug": "lithuania",
    "flag": "🇱🇹",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Luxembourg",
    "official_name": "Grand Duchy of Luxembourg",
    "common_name": "Luxembourg",
    "alpha2": "LU",
    "alpha3": "LUX",
    "numeric": "442",
    "slug": "luxembourg",
    "flag": "🇱🇺",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Macao",
    "official_name": "Macao Special Administrative Region of China",
    "common_name": "Macao",
    "alpha2": "MO",
    "alpha3": "MAC",
    "numeric": "446",
    "slug": "macao",
    "flag": "🇲🇴",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Madagascar",
    "official_name": "Republic of Madagascar",
    "common_name": "Madagascar",
    "alpha2": "MG",
    "alpha3": "MDG",
    "numeric": "450",
    "slug": "madagascar",
    "flag": "🇲🇬",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Malawi",
    "official_name": "Republic of Malawi",
    "common_name": "Malawi",
    "alpha2": "MW",
    "alpha3": "MWI",
    "numeric": "454",
    "slug": "malawi",
    "flag": "🇲🇼",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Malaysia",
    "official_name": "Malaysia",
    "common_name": "Malaysia",
    "alpha2": "MY",
    "alpha3": "MYS",
    "numeric": "458",
    "slug": "malaysia",
    "flag": "🇲🇾",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Maldives",
    "official_name": "Republic of Maldives",
    "common_name": "Maldives",
    "alpha2": "MV",
    "alpha3": "MDV",
    "numeric": "462",
    "slug": "maldives",
    "flag": "🇲🇻",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Mali",
    "official_name": "Republic of Mali",
    "common_name": "Mali",
    "alpha2": "ML",
    "alpha3": "MLI",
    "numeric": "466",
    "slug": "mali",
    "flag": "🇲🇱",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Malta",
    "official_name": "Republic of Malta",
    "common_name": "Malta",
    "alpha2": "MT",
    "alpha3": "MLT",
    "numeric": "470",
    "slug": "malta",
    "flag": "🇲🇹",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Marshall Islands",
    "official_name": "Republic of the Marshall Islands",
    "common_name": "Marshall Islands",
    "alpha2": "MH",
    "alpha3": "MHL",
    "numeric": "584",
    "slug": "marshall-islands",
    "flag": "🇲🇭",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Martinique",
    "official_name": "Martinique",
    "common_name": "Martinique",
    "alpha2": "MQ",
    "alpha3": "MTQ",
    "numeric": "474",
    "slug": "martinique",
    "flag": "🇲🇶",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Mauritania",
    "official_name": "Islamic Republic of Mauritania",
    "common_name": "Mauritania",
    "alpha2": "MR",
    "alpha3": "MRT",
    "numeric": "478",
    "slug": "mauritania",
    "flag": "🇲🇷",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Mauritius",
    "official_name": "Republic of Mauritius",
    "common_name": "Mauritius",
    "alpha2": "MU",
    "alpha3": "MUS",
    "numeric": "480",
    "slug": "mauritius",
    "flag": "🇲🇺",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Mayotte",
    "official_name": "Mayotte",
    "common_name": "Mayotte",
    "alpha2": "YT",
    "alpha3": "MYT",
    "numeric": "175",
    "slug": "mayotte",
    "flag": "🇾🇹",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Mexico",
    "official_name": "United Mexican States",
    "common_name": "Mexico",
    "alpha2": "MX",
    "alpha3": "MEX",
    "numeric": "484",
    "slug": "mexico",
    "flag": "🇲🇽",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Micronesia, Federated States of",
    "official_name": "Federated States of Micronesia",
    "common_name": "Micronesia, Federated States of",
    "alpha2": "FM",
    "alpha3": "FSM",
    "numeric": "583",
    "slug": "micronesia-federated-states-of",
    "flag": "🇫🇲",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Moldova, Republic of",
    "official_name": "Republic of Moldova",
    "common_name": "Moldova",
    "alpha2": "MD",
    "alpha3": "MDA",
    "numeric": "498",
    "slug": "moldova-republic-of",
    "flag": "🇲🇩",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Monaco",
    "official_name": "Principality of Monaco",
    "common_name": "Monaco",
    "alpha2": "MC",
    "alpha3": "MCO",
    "numeric": "492",
    "slug": "monaco",
    "flag": "🇲🇨",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Mongolia",
    "official_name": "Mongolia",
    "common_name": "Mongolia",
    "alpha2": "MN",
    "alpha3": "MNG",
    "numeric": "496",
    "slug": "mongolia",
    "flag": "🇲🇳",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Montenegro",
    "official_name": "Montenegro",
    "common_name": "Montenegro",
    "alpha2": "ME",
    "alpha3": "MNE",
    "numeric": "499",
    "slug": "montenegro",
    "flag": "🇲🇪",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Montserrat",
    "official_name": "Montserrat",
    "common_name": "Montserrat",
    "alpha2": "MS",
    "alpha3": "MSR",
    "numeric": "500",
    "slug": "montserrat",
    "flag": "🇲🇸",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Morocco",
    "official_name": "Kingdom of Morocco",
    "common_name": "Morocco",
    "alpha2": "MA",
    "alpha3": "MAR",
    "numeric": "504",
    "slug": "morocco",
    "flag": "🇲🇦",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Mozambique",
    "official_name": "Republic of Mozambique",
    "common_name": "Mozambique",
    "alpha2": "MZ",
    "alpha3": "MOZ",
    "numeric": "508",
    "slug": "mozambique",
    "flag": "🇲🇿",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Myanmar",
    "official_name": "Republic of Myanmar",
    "common_name": "Myanmar",
    "alpha2": "MM",
    "alpha3": "MMR",
    "numeric": "104",
    "slug": "myanmar",
    "flag": "🇲🇲",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Namibia",
    "official_name": "Republic of Namibia",
    "common_name": "Namibia",
    "alpha2": "NA",
    "alpha3": "NAM",
    "numeric": "516",
    "slug": "namibia",
    "flag": "🇳🇦",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Nauru",
    "official_name": "Republic of Nauru",
    "common_name": "Nauru",
    "alpha2": "NR",
    "alpha3": "NRU",
    "numeric": "520",
    "slug": "nauru",
    "flag": "🇳🇷",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Nepal",
    "official_name": "Federal Democratic Republic of Nepal",
    "common_name": "Nepal",
    "alpha2": "NP",
    "alpha3": "NPL",
    "numeric": "524",
    "slug": "nepal",
    "flag": "🇳🇵",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Netherlands",
    "official_name": "Kingdom of the Netherlands",
    "common_name": "Netherlands",
    "alpha2": "NL",
    "alpha3": "NLD",
    "numeric": "528",
    "slug": "netherlands",
    "flag": "🇳🇱",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "New Caledonia",
    "official_name": "New Caledonia",
    "common_name": "New Caledonia",
    "alpha2": "NC",
    "alpha3": "NCL",
    "numeric": "540",
    "slug": "new-caledonia",
    "flag": "🇳🇨",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "New Zealand",
    "official_name": "New Zealand",
    "common_name": "New Zealand",
    "alpha2": "NZ",
    "alpha3": "NZL",
    "numeric": "554",
    "slug": "new-zealand",
    "flag": "🇳🇿",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Nicaragua",
    "official_name": "Republic of Nicaragua",
    "common_name": "Nicaragua",
    "alpha2": "NI",
    "alpha3": "NIC",
    "numeric": "558",
    "slug": "nicaragua",
    "flag": "🇳🇮",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Niger",
    "official_name": "Republic of the Niger",
    "common_name": "Niger",
    "alpha2": "NE",
    "alpha3": "NER",
    "numeric": "562",
    "slug": "niger",
    "flag": "🇳🇪",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Nigeria",
    "official_name": "Federal Republic of Nigeria",
    "common_name": "Nigeria",
    "alpha2": "NG",
    "alpha3": "NGA",
    "numeric": "566",
    "slug": "nigeria",
    "flag": "🇳🇬",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Niue",
    "official_name": "Niue",
    "common_name": "Niue",
    "alpha2": "NU",
    "alpha3": "NIU",
    "numeric": "570",
    "slug": "niue",
    "flag": "🇳🇺",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Norfolk Island",
    "official_name": "Norfolk Island",
    "common_name": "Norfolk Island",
    "alpha2": "NF",
    "alpha3": "NFK",
    "numeric": "574",
    "slug": "norfolk-island",
    "flag": "🇳🇫",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "North Macedonia",
    "official_name": "Republic of North Macedonia",
    "common_name": "North Macedonia",
    "alpha2": "MK",
    "alpha3": "MKD",
    "numeric": "807",
    "slug": "north-macedonia",
    "flag": "🇲🇰",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Northern Mariana Islands",
    "official_name": "Commonwealth of the Northern Mariana Islands",
    "common_name": "Northern Mariana Islands",
    "alpha2": "MP",
    "alpha3": "MNP",
    "numeric": "580",
    "slug": "northern-mariana-islands",
    "flag": "🇲🇵",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Norway",
    "official_name": "Kingdom of Norway",
    "common_name": "Norway",
    "alpha2": "NO",
    "alpha3": "NOR",
    "numeric": "578",
    "slug": "norway",
    "flag": "🇳🇴",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Oman",
    "official_name": "Sultanate of Oman",
    "common_name": "Oman",
    "alpha2": "OM",
    "alpha3": "OMN",
    "numeric": "512",
    "slug": "oman",
    "flag": "🇴🇲",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Pakistan",
    "official_name": "Islamic Republic of Pakistan",
    "common_name": "Pakistan",
    "alpha2": "PK",
    "alpha3": "PAK",
    "numeric": "586",
    "slug": "pakistan",
    "flag": "🇵🇰",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Palau",
    "official_name": "Republic of Palau",
    "common_name": "Palau",
    "alpha2": "PW",
    "alpha3": "PLW",
    "numeric": "585",
    "slug": "palau",
    "flag": "🇵🇼",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Palestine, State of",
    "official_name": "the State of Palestine",
    "common_name": "Palestine, State of",
    "alpha2": "PS",
    "alpha3": "PSE",
    "numeric": "275",
    "slug": "palestine-state-of",
    "flag": "🇵🇸",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Panama",
    "official_name": "Republic of Panama",
    "common_name": "Panama",
    "alpha2": "PA",
    "alpha3": "PAN",
    "numeric": "591",
    "slug": "panama",
    "flag": "🇵🇦",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Papua New Guinea",
    "official_name": "Independent State of Papua New Guinea",
    "common_name": "Papua New Guinea",
    "alpha2": "PG",
    "alpha3": "PNG",
    "numeric": "598",
    "slug": "papua-new-guinea",
    "flag": "🇵🇬",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Paraguay",
    "official_name": "Republic of Paraguay",
    "common_name": "Paraguay",
    "alpha2": "PY",
    "alpha3": "PRY",
    "numeric": "600",
    "slug": "paraguay",
    "flag": "🇵🇾",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Peru",
    "official_name": "Republic of Peru",
    "common_name": "Peru",
    "alpha2": "PE",
    "alpha3": "PER",
    "numeric": "604",
    "slug": "peru",
    "flag": "🇵🇪",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Philippines",
    "official_name": "Republic of the Philippines",
    "common_name": "Philippines",
    "alpha2": "PH",
    "alpha3": "PHL",
    "numeric": "608",
    "slug": "philippines",
    "flag": "🇵🇭",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Pitcairn",
    "official_name": "Pitcairn",
    "common_name": "Pitcairn",
    "alpha2": "PN",
    "alpha3": "PCN",
    "numeric": "612",
    "slug": "pitcairn",
    "flag": "🇵🇳",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Poland",
    "official_name": "Republic of Poland",
    "common_name": "Poland",
    "alpha2": "PL",
    "alpha3": "POL",
    "numeric": "616",
    "slug": "poland",
    "flag": "🇵🇱",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Portugal",
    "official_name": "Portuguese Republic",
    "common_name": "Portugal",
    "alpha2": "PT",
    "alpha3": "PRT",
    "numeric": "620",
    "slug": "portugal",
    "flag": "🇵🇹",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Puerto Rico",
    "official_name": "Puerto Rico",
    "common_name": "Puerto Rico",
    "alpha2": "PR",
    "alpha3": "PRI",
    "numeric": "630",
    "slug": "puerto-rico",
    "flag": "🇵🇷",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Qatar",
    "official_name": "State of Qatar",
    "common_name": "Qatar",
    "alpha2": "QA",
    "alpha3": "QAT",
    "numeric": "634",
    "slug": "qatar",
    "flag": "🇶🇦",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Romania",
    "official_name": "Romania",
    "common_name": "Romania",
    "alpha2": "RO",
    "alpha3": "ROU",
    "numeric": "642",
    "slug": "romania",
    "flag": "🇷🇴",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Russian Federation",
    "official_name": "Russian Federation",
    "common_name": "Russian Federation",
    "alpha2": "RU",
    "alpha3": "RUS",
    "numeric": "643",
    "slug": "russian-federation",
    "flag": "🇷🇺",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Rwanda",
    "official_name": "Rwandese Republic",
    "common_name": "Rwanda",
    "alpha2": "RW",
    "alpha3": "RWA",
    "numeric": "646",
    "slug": "rwanda",
    "flag": "🇷🇼",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Réunion",
    "official_name": "Réunion",
    "common_name": "Réunion",
    "alpha2": "RE",
    "alpha3": "REU",
    "numeric": "638",
    "slug": "r-union",
    "flag": "🇷🇪",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Saint Barthélemy",
    "official_name": "Saint Barthélemy",
    "common_name": "Saint Barthélemy",
    "alpha2": "BL",
    "alpha3": "BLM",
    "numeric": "652",
    "slug": "saint-barth-lemy",
    "flag": "🇧🇱",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Saint Helena, Ascension and Tristan da Cunha",
    "official_name": "Saint Helena, Ascension and Tristan da Cunha",
    "common_name": "Saint Helena, Ascension and Tristan da Cunha",
    "alpha2": "SH",
    "alpha3": "SHN",
    "numeric": "654",
    "slug": "saint-helena-ascension-and-tristan-da-cunha",
    "flag": "🇸🇭",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Saint Kitts and Nevis",
    "official_name": "Saint Kitts and Nevis",
    "common_name": "Saint Kitts and Nevis",
    "alpha2": "KN",
    "alpha3": "KNA",
    "numeric": "659",
    "slug": "saint-kitts-and-nevis",
    "flag": "🇰🇳",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Saint Lucia",
    "official_name": "Saint Lucia",
    "common_name": "Saint Lucia",
    "alpha2": "LC",
    "alpha3": "LCA",
    "numeric": "662",
    "slug": "saint-lucia",
    "flag": "🇱🇨",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Saint Martin (French part)",
    "official_name": "Saint Martin (French part)",
    "common_name": "Saint Martin (French part)",
    "alpha2": "MF",
    "alpha3": "MAF",
    "numeric": "663",
    "slug": "saint-martin-french-part",
    "flag": "🇲🇫",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Saint Pierre and Miquelon",
    "official_name": "Saint Pierre and Miquelon",
    "common_name": "Saint Pierre and Miquelon",
    "alpha2": "PM",
    "alpha3": "SPM",
    "numeric": "666",
    "slug": "saint-pierre-and-miquelon",
    "flag": "🇵🇲",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Saint Vincent and the Grenadines",
    "official_name": "Saint Vincent and the Grenadines",
    "common_name": "Saint Vincent and the Grenadines",
    "alpha2": "VC",
    "alpha3": "VCT",
    "numeric": "670",
    "slug": "saint-vincent-and-the-grenadines",
    "flag": "🇻🇨",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Samoa",
    "official_name": "Independent State of Samoa",
    "common_name": "Samoa",
    "alpha2": "WS",
    "alpha3": "WSM",
    "numeric": "882",
    "slug": "samoa",
    "flag": "🇼🇸",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "San Marino",
    "official_name": "Republic of San Marino",
    "common_name": "San Marino",
    "alpha2": "SM",
    "alpha3": "SMR",
    "numeric": "674",
    "slug": "san-marino",
    "flag": "🇸🇲",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Sao Tome and Principe",
    "official_name": "Democratic Republic of Sao Tome and Principe",
    "common_name": "Sao Tome and Principe",
    "alpha2": "ST",
    "alpha3": "STP",
    "numeric": "678",
    "slug": "sao-tome-and-principe",
    "flag": "🇸🇹",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Saudi Arabia",
    "official_name": "Kingdom of Saudi Arabia",
    "common_name": "Saudi Arabia",
    "alpha2": "SA",
    "alpha3": "SAU",
    "numeric": "682",
    "slug": "saudi-arabia",
    "flag": "🇸🇦",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Senegal",
    "official_name": "Republic of Senegal",
    "common_name": "Senegal",
    "alpha2": "SN",
    "alpha3": "SEN",
    "numeric": "686",
    "slug": "senegal",
    "flag": "🇸🇳",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Serbia",
    "official_name": "Republic of Serbia",
    "common_name": "Serbia",
    "alpha2": "RS",
    "alpha3": "SRB",
    "numeric": "688",
    "slug": "serbia",
    "flag": "🇷🇸",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Seychelles",
    "official_name": "Republic of Seychelles",
    "common_name": "Seychelles",
    "alpha2": "SC",
    "alpha3": "SYC",
    "numeric": "690",
    "slug": "seychelles",
    "flag": "🇸🇨",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Sierra Leone",
    "official_name": "Republic of Sierra Leone",
    "common_name": "Sierra Leone",
    "alpha2": "SL",
    "alpha3": "SLE",
    "numeric": "694",
    "slug": "sierra-leone",
    "flag": "🇸🇱",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Singapore",
    "official_name": "Republic of Singapore",
    "common_name": "Singapore",
    "alpha2": "SG",
    "alpha3": "SGP",
    "numeric": "702",
    "slug": "singapore",
    "flag": "🇸🇬",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Sint Maarten (Dutch part)",
    "official_name": "Sint Maarten (Dutch part)",
    "common_name": "Sint Maarten (Dutch part)",
    "alpha2": "SX",
    "alpha3": "SXM",
    "numeric": "534",
    "slug": "sint-maarten-dutch-part",
    "flag": "🇸🇽",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Slovakia",
    "official_name": "Slovak Republic",
    "common_name": "Slovakia",
    "alpha2": "SK",
    "alpha3": "SVK",
    "numeric": "703",
    "slug": "slovakia",
    "flag": "🇸🇰",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Slovenia",
    "official_name": "Republic of Slovenia",
    "common_name": "Slovenia",
    "alpha2": "SI",
    "alpha3": "SVN",
    "numeric": "705",
    "slug": "slovenia",
    "flag": "🇸🇮",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Solomon Islands",
    "official_name": "Solomon Islands",
    "common_name": "Solomon Islands",
    "alpha2": "SB",
    "alpha3": "SLB",
    "numeric": "090",
    "slug": "solomon-islands",
    "flag": "🇸🇧",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Somalia",
    "official_name": "Federal Republic of Somalia",
    "common_name": "Somalia",
    "alpha2": "SO",
    "alpha3": "SOM",
    "numeric": "706",
    "slug": "somalia",
    "flag": "🇸🇴",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "South Africa",
    "official_name": "Republic of South Africa",
    "common_name": "South Africa",
    "alpha2": "ZA",
    "alpha3": "ZAF",
    "numeric": "710",
    "slug": "south-africa",
    "flag": "🇿🇦",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "South Georgia and the South Sandwich Islands",
    "official_name": "South Georgia and the South Sandwich Islands",
    "common_name": "South Georgia and the South Sandwich Islands",
    "alpha2": "GS",
    "alpha3": "SGS",
    "numeric": "239",
    "slug": "south-georgia-and-the-south-sandwich-islands",
    "flag": "🇬🇸",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "South Sudan",
    "official_name": "Republic of South Sudan",
    "common_name": "South Sudan",
    "alpha2": "SS",
    "alpha3": "SSD",
    "numeric": "728",
    "slug": "south-sudan",
    "flag": "🇸🇸",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Spain",
    "official_name": "Kingdom of Spain",
    "common_name": "Spain",
    "alpha2": "ES",
    "alpha3": "ESP",
    "numeric": "724",
    "slug": "spain",
    "flag": "🇪🇸",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Sri Lanka",
    "official_name": "Democratic Socialist Republic of Sri Lanka",
    "common_name": "Sri Lanka",
    "alpha2": "LK",
    "alpha3": "LKA",
    "numeric": "144",
    "slug": "sri-lanka",
    "flag": "🇱🇰",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Sudan",
    "official_name": "Republic of the Sudan",
    "common_name": "Sudan",
    "alpha2": "SD",
    "alpha3": "SDN",
    "numeric": "729",
    "slug": "sudan",
    "flag": "🇸🇩",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Suriname",
    "official_name": "Republic of Suriname",
    "common_name": "Suriname",
    "alpha2": "SR",
    "alpha3": "SUR",
    "numeric": "740",
    "slug": "suriname",
    "flag": "🇸🇷",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Svalbard and Jan Mayen",
    "official_name": "Svalbard and Jan Mayen",
    "common_name": "Svalbard and Jan Mayen",
    "alpha2": "SJ",
    "alpha3": "SJM",
    "numeric": "744",
    "slug": "svalbard-and-jan-mayen",
    "flag": "🇸🇯",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Sweden",
    "official_name": "Kingdom of Sweden",
    "common_name": "Sweden",
    "alpha2": "SE",
    "alpha3": "SWE",
    "numeric": "752",
    "slug": "sweden",
    "flag": "🇸🇪",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Switzerland",
    "official_name": "Swiss Confederation",
    "common_name": "Switzerland",
    "alpha2": "CH",
    "alpha3": "CHE",
    "numeric": "756",
    "slug": "switzerland",
    "flag": "🇨🇭",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Syrian Arab Republic",
    "official_name": "Syrian Arab Republic",
    "common_name": "Syria",
    "alpha2": "SY",
    "alpha3": "SYR",
    "numeric": "760",
    "slug": "syrian-arab-republic",
    "flag": "🇸🇾",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Taiwan, Province of China",
    "official_name": "Taiwan, Province of China",
    "common_name": "Taiwan",
    "alpha2": "TW",
    "alpha3": "TWN",
    "numeric": "158",
    "slug": "taiwan-province-of-china",
    "flag": "🇹🇼",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Tajikistan",
    "official_name": "Republic of Tajikistan",
    "common_name": "Tajikistan",
    "alpha2": "TJ",
    "alpha3": "TJK",
    "numeric": "762",
    "slug": "tajikistan",
    "flag": "🇹🇯",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Tanzania, United Republic of",
    "official_name": "United Republic of Tanzania",
    "common_name": "Tanzania",
    "alpha2": "TZ",
    "alpha3": "TZA",
    "numeric": "834",
    "slug": "tanzania-united-republic-of",
    "flag": "🇹🇿",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Thailand",
    "official_name": "Kingdom of Thailand",
    "common_name": "Thailand",
    "alpha2": "TH",
    "alpha3": "THA",
    "numeric": "764",
    "slug": "thailand",
    "flag": "🇹🇭",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Timor-Leste",
    "official_name": "Democratic Republic of Timor-Leste",
    "common_name": "Timor-Leste",
    "alpha2": "TL",
    "alpha3": "TLS",
    "numeric": "626",
    "slug": "timor-leste",
    "flag": "🇹🇱",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Togo",
    "official_name": "Togolese Republic",
    "common_name": "Togo",
    "alpha2": "TG",
    "alpha3": "TGO",
    "numeric": "768",
    "slug": "togo",
    "flag": "🇹🇬",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Tokelau",
    "official_name": "Tokelau",
    "common_name": "Tokelau",
    "alpha2": "TK",
    "alpha3": "TKL",
    "numeric": "772",
    "slug": "tokelau",
    "flag": "🇹🇰",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Tonga",
    "official_name": "Kingdom of Tonga",
    "common_name": "Tonga",
    "alpha2": "TO",
    "alpha3": "TON",
    "numeric": "776",
    "slug": "tonga",
    "flag": "🇹🇴",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Trinidad and Tobago",
    "official_name": "Republic of Trinidad and Tobago",
    "common_name": "Trinidad and Tobago",
    "alpha2": "TT",
    "alpha3": "TTO",
    "numeric": "780",
    "slug": "trinidad-and-tobago",
    "flag": "🇹🇹",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Tunisia",
    "official_name": "Republic of Tunisia",
    "common_name": "Tunisia",
    "alpha2": "TN",
    "alpha3": "TUN",
    "numeric": "788",
    "slug": "tunisia",
    "flag": "🇹🇳",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Turkmenistan",
    "official_name": "Turkmenistan",
    "common_name": "Turkmenistan",
    "alpha2": "TM",
    "alpha3": "TKM",
    "numeric": "795",
    "slug": "turkmenistan",
    "flag": "🇹🇲",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Turks and Caicos Islands",
    "official_name": "Turks and Caicos Islands",
    "common_name": "Turks and Caicos Islands",
    "alpha2": "TC",
    "alpha3": "TCA",
    "numeric": "796",
    "slug": "turks-and-caicos-islands",
    "flag": "🇹🇨",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Tuvalu",
    "official_name": "Tuvalu",
    "common_name": "Tuvalu",
    "alpha2": "TV",
    "alpha3": "TUV",
    "numeric": "798",
    "slug": "tuvalu",
    "flag": "🇹🇻",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Türkiye",
    "official_name": "Republic of Türkiye",
    "common_name": "Türkiye",
    "alpha2": "TR",
    "alpha3": "TUR",
    "numeric": "792",
    "slug": "t-rkiye",
    "flag": "🇹🇷",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Uganda",
    "official_name": "Republic of Uganda",
    "common_name": "Uganda",
    "alpha2": "UG",
    "alpha3": "UGA",
    "numeric": "800",
    "slug": "uganda",
    "flag": "🇺🇬",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Ukraine",
    "official_name": "Ukraine",
    "common_name": "Ukraine",
    "alpha2": "UA",
    "alpha3": "UKR",
    "numeric": "804",
    "slug": "ukraine",
    "flag": "🇺🇦",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "United Arab Emirates",
    "official_name": "United Arab Emirates",
    "common_name": "United Arab Emirates",
    "alpha2": "AE",
    "alpha3": "ARE",
    "numeric": "784",
    "slug": "united-arab-emirates",
    "flag": "🇦🇪",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "United Kingdom",
    "official_name": "United Kingdom of Great Britain and Northern Ireland",
    "common_name": "United Kingdom",
    "alpha2": "GB",
    "alpha3": "GBR",
    "numeric": "826",
    "slug": "united-kingdom",
    "flag": "🇬🇧",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "United States",
    "official_name": "United States of America",
    "common_name": "United States",
    "alpha2": "US",
    "alpha3": "USA",
    "numeric": "840",
    "slug": "united-states",
    "flag": "🇺🇸",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "United States Minor Outlying Islands",
    "official_name": "United States Minor Outlying Islands",
    "common_name": "United States Minor Outlying Islands",
    "alpha2": "UM",
    "alpha3": "UMI",
    "numeric": "581",
    "slug": "united-states-minor-outlying-islands",
    "flag": "🇺🇲",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Uruguay",
    "official_name": "Eastern Republic of Uruguay",
    "common_name": "Uruguay",
    "alpha2": "UY",
    "alpha3": "URY",
    "numeric": "858",
    "slug": "uruguay",
    "flag": "🇺🇾",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Uzbekistan",
    "official_name": "Republic of Uzbekistan",
    "common_name": "Uzbekistan",
    "alpha2": "UZ",
    "alpha3": "UZB",
    "numeric": "860",
    "slug": "uzbekistan",
    "flag": "🇺🇿",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Vanuatu",
    "official_name": "Republic of Vanuatu",
    "common_name": "Vanuatu",
    "alpha2": "VU",
    "alpha3": "VUT",
    "numeric": "548",
    "slug": "vanuatu",
    "flag": "🇻🇺",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Venezuela, Bolivarian Republic of",
    "official_name": "Bolivarian Republic of Venezuela",
    "common_name": "Venezuela",
    "alpha2": "VE",
    "alpha3": "VEN",
    "numeric": "862",
    "slug": "venezuela-bolivarian-republic-of",
    "flag": "🇻🇪",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Viet Nam",
    "official_name": "Socialist Republic of Viet Nam",
    "common_name": "Vietnam",
    "alpha2": "VN",
    "alpha3": "VNM",
    "numeric": "704",
    "slug": "viet-nam",
    "flag": "🇻🇳",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Virgin Islands, British",
    "official_name": "British Virgin Islands",
    "common_name": "Virgin Islands, British",
    "alpha2": "VG",
    "alpha3": "VGB",
    "numeric": "092",
    "slug": "virgin-islands-british",
    "flag": "🇻🇬",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Virgin Islands, U.S.",
    "official_name": "Virgin Islands of the United States",
    "common_name": "Virgin Islands, U.S.",
    "alpha2": "VI",
    "alpha3": "VIR",
    "numeric": "850",
    "slug": "virgin-islands-u-s",
    "flag": "🇻🇮",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Wallis and Futuna",
    "official_name": "Wallis and Futuna",
    "common_name": "Wallis and Futuna",
    "alpha2": "WF",
    "alpha3": "WLF",
    "numeric": "876",
    "slug": "wallis-and-futuna",
    "flag": "🇼🇫",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Western Sahara",
    "official_name": "Western Sahara",
    "common_name": "Western Sahara",
    "alpha2": "EH",
    "alpha3": "ESH",
    "numeric": "732",
    "slug": "western-sahara",
    "flag": "🇪🇭",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Yemen",
    "official_name": "Republic of Yemen",
    "common_name": "Yemen",
    "alpha2": "YE",
    "alpha3": "YEM",
    "numeric": "887",
    "slug": "yemen",
    "flag": "🇾🇪",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Zambia",
    "official_name": "Republic of Zambia",
    "common_name": "Zambia",
    "alpha2": "ZM",
    "alpha3": "ZMB",
    "numeric": "894",
    "slug": "zambia",
    "flag": "🇿🇲",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Zimbabwe",
    "official_name": "Republic of Zimbabwe",
    "common_name": "Zimbabwe",
    "alpha2": "ZW",
    "alpha3": "ZWE",
    "numeric": "716",
    "slug": "zimbabwe",
    "flag": "🇿🇼",
    "iso_standard": "ISO 3166-1"
  },
  {
    "name": "Åland Islands",
    "official_name": "Åland Islands",
    "common_name": "Åland Islands",
    "alpha2": "AX",
    "alpha3": "ALA",
    "numeric": "248",
    "slug": "land-islands",
    "flag": "🇦🇽",
    "iso_standard": "ISO 3166-1"
  }
];

export const airports = [
  {
    "iata": "YYZ",
    "icao": "CYYZ",
    "name": "Toronto Pearson International Airport",
    "city": "Toronto",
    "country": "Canada",
    "country_code": "CA",
    "latitude": 43.6777,
    "longitude": -79.6248
  },
  {
    "iata": "YVR",
    "icao": "CYVR",
    "name": "Vancouver International Airport",
    "city": "Vancouver",
    "country": "Canada",
    "country_code": "CA",
    "latitude": 49.1967,
    "longitude": -123.1815
  },
  {
    "iata": "YUL",
    "icao": "CYUL",
    "name": "Montréal–Trudeau International Airport",
    "city": "Montréal",
    "country": "Canada",
    "country_code": "CA",
    "latitude": 45.4706,
    "longitude": -73.7408
  },
  {
    "iata": "JFK",
    "icao": "KJFK",
    "name": "John F. Kennedy International Airport",
    "city": "New York",
    "country": "United States",
    "country_code": "US",
    "latitude": 40.6413,
    "longitude": -73.7781
  },
  {
    "iata": "LAX",
    "icao": "KLAX",
    "name": "Los Angeles International Airport",
    "city": "Los Angeles",
    "country": "United States",
    "country_code": "US",
    "latitude": 33.9416,
    "longitude": -118.4085
  },
  {
    "iata": "LHR",
    "icao": "EGLL",
    "name": "London Heathrow Airport",
    "city": "London",
    "country": "United Kingdom",
    "country_code": "GB",
    "latitude": 51.47,
    "longitude": -0.4543
  },
  {
    "iata": "CDG",
    "icao": "LFPG",
    "name": "Paris Charles de Gaulle Airport",
    "city": "Paris",
    "country": "France",
    "country_code": "FR",
    "latitude": 49.0097,
    "longitude": 2.5479
  },
  {
    "iata": "FRA",
    "icao": "EDDF",
    "name": "Frankfurt Airport",
    "city": "Frankfurt",
    "country": "Germany",
    "country_code": "DE",
    "latitude": 50.0379,
    "longitude": 8.5622
  },
  {
    "iata": "MAD",
    "icao": "LEMD",
    "name": "Adolfo Suárez Madrid–Barajas Airport",
    "city": "Madrid",
    "country": "Spain",
    "country_code": "ES",
    "latitude": 40.4983,
    "longitude": -3.5676
  },
  {
    "iata": "FCO",
    "icao": "LIRF",
    "name": "Rome Fiumicino Airport",
    "city": "Rome",
    "country": "Italy",
    "country_code": "IT",
    "latitude": 41.8003,
    "longitude": 12.2389
  },
  {
    "iata": "HND",
    "icao": "RJTT",
    "name": "Tokyo Haneda Airport",
    "city": "Tokyo",
    "country": "Japan",
    "country_code": "JP",
    "latitude": 35.5494,
    "longitude": 139.7798
  },
  {
    "iata": "SIN",
    "icao": "WSSS",
    "name": "Singapore Changi Airport",
    "city": "Singapore",
    "country": "Singapore",
    "country_code": "SG",
    "latitude": 1.3644,
    "longitude": 103.9915
  },
  {
    "iata": "DXB",
    "icao": "OMDB",
    "name": "Dubai International Airport",
    "city": "Dubai",
    "country": "United Arab Emirates",
    "country_code": "AE",
    "latitude": 25.2532,
    "longitude": 55.3657
  },
  {
    "iata": "SYD",
    "icao": "YSSY",
    "name": "Sydney Kingsford Smith Airport",
    "city": "Sydney",
    "country": "Australia",
    "country_code": "AU",
    "latitude": -33.9399,
    "longitude": 151.1753
  },
  {
    "iata": "GRU",
    "icao": "SBGR",
    "name": "São Paulo/Guarulhos International Airport",
    "city": "São Paulo",
    "country": "Brazil",
    "country_code": "BR",
    "latitude": -23.4356,
    "longitude": -46.4731
  },
  {
    "iata": "CPT",
    "icao": "FACT",
    "name": "Cape Town International Airport",
    "city": "Cape Town",
    "country": "South Africa",
    "country_code": "ZA",
    "latitude": -33.9715,
    "longitude": 18.6021
  }
];

export const airlines = [
  {
    "iata": "AC",
    "icao": "ACA",
    "name": "Air Canada",
    "country": "Canada",
    "country_code": "CA"
  },
  {
    "iata": "WS",
    "icao": "WJA",
    "name": "WestJet",
    "country": "Canada",
    "country_code": "CA"
  },
  {
    "iata": "AA",
    "icao": "AAL",
    "name": "American Airlines",
    "country": "United States",
    "country_code": "US"
  },
  {
    "iata": "DL",
    "icao": "DAL",
    "name": "Delta Air Lines",
    "country": "United States",
    "country_code": "US"
  },
  {
    "iata": "UA",
    "icao": "UAL",
    "name": "United Airlines",
    "country": "United States",
    "country_code": "US"
  },
  {
    "iata": "BA",
    "icao": "BAW",
    "name": "British Airways",
    "country": "United Kingdom",
    "country_code": "GB"
  },
  {
    "iata": "AF",
    "icao": "AFR",
    "name": "Air France",
    "country": "France",
    "country_code": "FR"
  },
  {
    "iata": "LH",
    "icao": "DLH",
    "name": "Lufthansa",
    "country": "Germany",
    "country_code": "DE"
  },
  {
    "iata": "IB",
    "icao": "IBE",
    "name": "Iberia",
    "country": "Spain",
    "country_code": "ES"
  },
  {
    "iata": "AZ",
    "icao": "ITY",
    "name": "ITA Airways",
    "country": "Italy",
    "country_code": "IT"
  },
  {
    "iata": "JL",
    "icao": "JAL",
    "name": "Japan Airlines",
    "country": "Japan",
    "country_code": "JP"
  },
  {
    "iata": "SQ",
    "icao": "SIA",
    "name": "Singapore Airlines",
    "country": "Singapore",
    "country_code": "SG"
  },
  {
    "iata": "EK",
    "icao": "UAE",
    "name": "Emirates",
    "country": "United Arab Emirates",
    "country_code": "AE"
  },
  {
    "iata": "QF",
    "icao": "QFA",
    "name": "Qantas",
    "country": "Australia",
    "country_code": "AU"
  },
  {
    "iata": "LA",
    "icao": "LAN",
    "name": "LATAM Airlines",
    "country": "Chile",
    "country_code": "CL"
  },
  {
    "iata": "ET",
    "icao": "ETH",
    "name": "Ethiopian Airlines",
    "country": "Ethiopia",
    "country_code": "ET"
  }
];

